# Generated by Django 6.0.7 on 2026-07-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
