# Generated by Django 6.0.7 on 2026-07-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
