# Generated by Django 6.0.7 on 2026-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_department_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('name', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('description', models.TextField()),
            ],
        ),
    ]
