# Generated by Django 6.0.7 on 2026-07-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('pages', models.CharField(max_length=100)),
                ('render', models.CharField(max_length=50)),
            ],
        ),
    ]
