# Generated by Django 6.0.7 on 2026-07-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='services',
            name='render',
        ),
    ]
