# Generated by Django 6.0.7 on 2026-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_services_pages_remove_services_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='render',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
