# Generated by Django 6.0.7 on 2026-07-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_reason_appointment_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='query',
        ),
    ]
