# Generated by Django 6.0.7 on 2026-07-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors/')),
                ('name', models.CharField(max_length=50)),
                ('specialist', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
