# Generated by Django 6.0.7 on 2026-07-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('pages', models.CharField(max_length=50)),
            ],
        ),
    ]
