# Generated by Django 6.0.7 on 2026-07-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='pages',
        ),
    ]
