# Generated by Django 6.0.7 on 2026-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_department_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors/')),
                ('name', models.CharField(max_length=50)),
                ('specialist', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
